### PR TITLE
Warn if files are too big

### LINKED ISSUE #58: warn if source distribution has big files
When building the docker image, we compress the user's code (`.tar.gz` file) and copy it into the image, here's the [implementation](https://github.com/ploomber/soopervisor/blob/b230a5bb415dd4e9b05e1448b21b17c2150dc75c/src/soopervisor/commons/source.py#L97).

The function already ignores things that [shouldn't be copied into the image,](https://github.com/ploomber/soopervisor/blob/b230a5bb415dd4e9b05e1448b21b17c2150dc75c/src/soopervisor/commons/source.py#L160) like `__pycache__` files or the git repository. These are clear examples of things that shouldn't go into the image but there are ambiguous cases.

For example, a user might be storing raw data in some `raw/` folder and the function will copy them, making the docker image unnecessarily big. In many cases, this would be a mistake and we should warn the user, but in other cases, the user indeed might want to include those files (so we shouldn't throw an error just because of this)

So we should warn the user if big files end up in the folder they will get copied. we should modify the copying function and print a warning message in yellow color if we detect files above a certain threshold. 10 MB is a reasonable threshold

### PR DESCRIPTION
**Pull request by Wxl19980214**
## Describe your changes
Added a check for big files and issue warnings
## Issue ticket number and link
Closes #58 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

### CODE REVIEW

**Comment by Wxl19980214** [comment]
Passed local test. But I haven't try it out for real. There's something wrong the tutorial and I cannot run it.

**Comment by edublancas** [comment]
hey. yeah, people are having issues with the soopervisor tutorial and we haven't fixed them.

but you can test without following the full tutorial, check this out https://soopervisor.readthedocs.io/en/latest/cookbook/kubernetes.html

**Comment by Wxl19980214** [comment]
Tested, ready for review

**Comment by idomic** [comment]
@Wxl19980214 one of the tests is failing: test_copy_warn_if_file_too_big

**Comment by Wxl19980214** [comment]
checking

**Comment by Wxl19980214** [comment]
It's windows thing. The directory format is dir\\file for windows but dir/file for linux and macOs. I will just remove it

**Comment by Wxl19980214** [comment]
Ready to run workflow

**Comment by edublancas** [comment]
approved running workflow

**Comment by idomic** [comment]
LGTM, nice work!

**Pull request merged**
